name: food_bridge
description: "A Flutter food delivery application."

# Prevent accidental publishing to pub.dev
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  shared_preferences: ^2.2.0

  # State Management
  provider:
    ^6.1.1

    # Google Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  location: ^5.0.3
  geocoding: ^2.1.1

  # UI Components
  cupertino_icons: ^1.0.8

  # HTTP & API
  http: ^1.1.0

  # Image handling
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  firebase_storage: ^13.0.3

  # Utils
  intl: ^0.18.1
  midtrans_sdk: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Assets (uncomment when you have actual assets)
  assets:
    #   - assets/images/
    - assets/images/aicream.png
    - assets/images/eskrim.jpg
    - assets/images/ph1.jpg
    - assets/images/mieayam.jpg
    - assets/images/anekajus.jpg
    - assets/images/baso.jpg
    - assets/images/eskelapa.jpg
    - assets/images/jusbuah.jpg
    - assets/images/jussehat.jpg
    - assets/images/kopi.jpg
    - assets/images/mathcajus.jpg
    - assets/images/mieayam.jpg
    - assets/images/nasigoreng.jpg
    - assets/images/nasikuning.jpg
    - assets/images/nasiuduk.jpg
    - assets/images/pecellele.jpg
    - assets/images/roti'i.jpg
    - assets/images/satepadang.jpg
    - assets/images/soto.jpg
    - assets/images/eskrim2.jpg
    - assets/images/roti2.jpg
    - assets/images/nasiuduk2.jpg
    - assets/images/mie2.jpg
    - assets/images/nasikuning2.jpg
    - assets/images/nasigoreng2.jpg
    - assets/images/gorengan.jpg
    - assets/images/soto2.jpg
    - assets/images/burger2.jpg
    - assets/images/gorengan2.jpg
    - assets/images/salad.jpg
    - assets/images/saladb.png
    # update
    - assets/images/bluenoodles.jpg
    - assets/images/bigspa.jpg
    - assets/images/ramena.jpg
    - assets/images/katsu1.jpg
    - assets/images/sushi21.jpg
    - assets/images/sushi22.jpg
    - assets/images/ramentpg.jpg
    - assets/images/sugardonat.jpg
    - assets/images/kitdonut.jpg
    - assets/images/rawdonut.jpg
    - assets/images/cocodonut.jpg
    - assets/images/rnbwdonut.jpg
    - assets/images/croisco.jpg
    - assets/images/sugarbread.jpg
    - assets/images/bobabread.jpg
    - assets/images/sugarbread_2.jpg
    - assets/images/dragonjus.jpg
    - assets/images/strosmo.jpg
    - assets/images/yellowrice2.jpg
    - assets/images/amperaf.jpg
    - assets/images/amperaf_2.jpg
    - assets/images/amperaf_3.jpg
    - assets/images/friedrice.jpg
    - assets/images/amperaf_4.jpg
    - assets/images/friedrice_2.jpg

    #   - assets/icons/
    - assets/icons/friedcat.png
    - assets/icons/burgercat.png
    - assets/icons/nasgorcat.png
    - assets/icons/nasningcat.png
    - assets/icons/sotocat.png
    - assets/icons/roticat.png
    - assets/icons/juscat.png
    - assets/icons/iscat.png
    - assets/icons/iccat.png
    - assets/icons/burger.png
    - assets/icons/bread.png
    - assets/icons/donuts.png
    - assets/icons/icecream.png
    - assets/icons/mie.png
    - assets/icons/salad.png
    - assets/icons/nasigoreng.png
    - assets/icons/gorengan.png
    - assets/icons/jus.png
    - assets/icons/more.png

  # Custom fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/burgercat.png"
